### PR TITLE
Version 2.4

### PR DESCRIPTION
**Pull request by Toflar**
* Dropped support for Symfony < 4.4
* Dropped support for PHP < 7.2
* Added support for PHP 8

What's your preferred release strategy?

🎉  = release as version 2.4, no type hints in interfaces for BC
🚀  = release as version 3.0, add type hints in interfaces and thus break BC

### CODE REVIEW

**Comment by Toflar** [comment]
Ping @alexander-schranz, @dbu, @chirimoya and @andrerom:

I want to release a version with PHP 8 support and keeping PHP 5.6 and Symfony < 4.4 support was just really too much PITA so I decided to release a new version which droppes support for those. None of these versions have active support anymore so I figured that would be an okay move.
I decided not to add return types to the interfaces so technically, I could release this as version 2.4.0. However, we could also go for a version 3.0 where I'd add those type hints.
For Contao we'd be okay with both, I guess. But I wanted to check with you guys and hear about your preferences?

**Comment by alexander-schranz** [comment]
The current @sulu version where we still give bugfix support and uses the PSR6Store is 2.1  which have also the minimum requirement of Symfony 4.4/5.0 and PHP 7.2.

> Dropping < 4.4 symfony and < php 7.2 is okay from our side. 👍 

We did not extend from the Psr6Store class or implement its Interfaces somewhere so the typehints will break nothing in sulu if you want to release it as 2.4.

And Thank you for your work we really appreciate it 🙏

**Comment by andrerom** [comment]
At Ibexa _(former eZ)_ we only use this in 3.x+, and it requires php 7.3+ and Symfony 5.1+

cc @ViniTou @mnocon

**Comment by Toflar** [comment]
Thanks for the feedback. I just still don't know whether to release 2.4 or 3.0 😄 I've updated the initial issue description so you can sort of vote by adding your emoji reactions. Can I ask you to vote for either one strategy, please? Cheers!

**Comment by andrerom** [comment]
I'll say 3.0, as Symfony 4.4 is in fact still supported for a long time..

**Comment by andrerom** [comment]
Unsure, it looks fine to me, but maybe @dbu knows of possible issues with a 2.4

**Comment by dbu** [comment]
if you add the typehints to public implementation methods, it is strictly speaking a BC break because the class is not final, so somebody could have extended the class.

if you want to do a 2.4 first, i'd revert the changes to public / protected method signatures even on the concrete class to be strict about BC.

so i would go with 3.0 and add typehints to the interfaces too. i expect most systems only consume these interfaces, and those don't need to adjust. adjustments are only needed when implementing the interfaces.

**Comment by Toflar** [comment]
Agreed. I also think it's generally speaking a good idea to release a new major version if you change the dependencies significantly. Just to make sure people actively change the version constraint.
I guess I'll got with v3 then :)

**Comment by Toflar** [comment]
Closed in favor of https://github.com/Toflar/psr6-symfony-http-cache-store/pull/38 and released version 3.0.0.
Thanks a lot everybody for all the feedback, you guys are the best! ❤️

**Pull request closed without merging**
